# Generated by Django 5.0 on 2023-12-31 20:10

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import menu.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuSet",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "hex_color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code, e.g., #RRGGBB",
                        max_length=7,
                        null=True,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "hex_color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code, e.g., #RRGGBB",
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "sub_categories",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to=models.Q(
                            ("id", models.F("id")), _negated=True
                        ),
                        related_name="parent_category",
                        to="menu.category",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="category", to="menu.product"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MenuSetsInOrderAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "menu_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="menu.menuset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateField(blank=True, null=True)),
                (
                    "order_id",
                    models.CharField(
                        default=menu.models.order_id_default,
                        editable=False,
                        max_length=255,
                    ),
                ),
                ("payment_method", models.CharField(default="CS", max_length=2)),
                ("is_paid", models.BooleanField(default=False)),
                ("delivery_method", models.CharField(default="HR", max_length=2)),
                (
                    "menu_sets",
                    models.ManyToManyField(
                        related_name="orders",
                        through="menu.MenuSetsInOrderAmount",
                        to="menu.menuset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="menusetsinorderamount",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="menu.order"
            ),
        ),
        migrations.CreateModel(
            name="OrderedProductsInMenuSetsOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering_number", models.PositiveIntegerField(default=0)),
                (
                    "menu_set_in_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="menu.menusetsinorderamount",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="menu.product",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("menu_set_in_order", "product", "ordering_number")
                },
            },
        ),
        migrations.AddField(
            model_name="menusetsinorderamount",
            name="products",
            field=models.ManyToManyField(
                through="menu.OrderedProductsInMenuSetsOrder", to="menu.product"
            ),
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="menus", to="menu.category"
                    ),
                ),
                (
                    "menu_sets",
                    models.ManyToManyField(
                        blank=True, related_name="menus", to="menu.menuset"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="menus", to="menu.product"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductInOrderAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="menu.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="menu.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "product")},
            },
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders",
                through="menu.ProductInOrderAmount",
                to="menu.product",
            ),
        ),
        migrations.CreateModel(
            name="MenuSetStep",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("ordering_number", models.PositiveIntegerField(default=0)),
                (
                    "menu_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="set_steps",
                        to="menu.menuset",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="menu_set_steps", to="menu.product"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "menu_set")},
            },
        ),
    ]
