# Generated by Django 5.0 on 2023-12-30 21:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_menuset_menu_menu_sets_menusetstep"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuSetsInOrderAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "menu_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="menu.menuset",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="menu.order"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="order",
            name="menu_sets",
            field=models.ManyToManyField(
                related_name="orders",
                through="menu.MenuSetsInOrderAmount",
                to="menu.menuset",
            ),
        ),
        migrations.CreateModel(
            name="OrderedProductsInMenuSetsOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering_number", models.PositiveIntegerField(default=0)),
                (
                    "menu_set_in_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="menu.menusetsinorderamount",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="menu.product",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("menu_set_in_order", "product", "ordering_number")
                },
            },
        ),
        migrations.AddField(
            model_name="menusetsinorderamount",
            name="products",
            field=models.ManyToManyField(
                through="menu.OrderedProductsInMenuSetsOrder", to="menu.product"
            ),
        ),
    ]
