name: Django Deploy CI

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v3 https://github.com/google-github-actions/deploy-appengine
    - name: deploy
      run: |
        cd backend
        echo TODO
